# Generated by Django 4.1.7 on 2023-03-20 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="Circle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="Doujinshi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                (
                    "origin_language",
                    models.CharField(
                        choices=[
                            (None, ""),
                            ("JAPANESE", "Japanese"),
                            ("CHINESE", "Chinese"),
                        ],
                        default=None,
                        max_length=8,
                    ),
                ),
                (
                    "present_language",
                    models.CharField(
                        choices=[
                            (None, ""),
                            ("JAPANESE", "Japanese"),
                            ("CHINESE", "Chinese"),
                        ],
                        default=None,
                        max_length=8,
                    ),
                ),
                ("buy_way", models.CharField(max_length=64)),
                ("buy_time", models.DateField(null=True)),
                ("price", models.PositiveIntegerField(null=True)),
                (
                    "price_currency",
                    models.CharField(
                        choices=[(None, ""), ("TWD", "TWD"), ("JPY", "JPY")],
                        default=None,
                        max_length=3,
                        null=True,
                    ),
                ),
                ("record_time", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="doujinshi.author",
                    ),
                ),
                (
                    "circle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="doujinshi.circle",
                    ),
                ),
            ],
        ),
    ]
